# File generated by cwl2click v{{ version }}
# timestamp: {{ timestamp }}

from datetime import datetime
from loguru import logger
from pathlib import Path

import click
import time

@click.command()
{% for input in process.inputs %}@click.option(
    "{{input.inputBinding.prefix}}"
)
{% endfor %}def main({% for input in process.inputs %}
    {{input.id | to_snake_case}},{% endfor %}
):
    start_time = time.time()

    logger.info("Executing {{process.id | to_snake_case}}:main")
    logger.info('------------------------------------------------------------------------')

    try:
        # TODO put you impl here

        logger.info('------------------------------------------------------------------------')
        logger.success('BUILD SUCCESS')
    except Exception as e:
        logger.info('------------------------------------------------------------------------')
        logger.error('BUILD FAILED')
        logger.error(f"An unexpected error occurred: {e}")

    end_time = time.time()

    logger.info('------------------------------------------------------------------------')
    logger.info(f"Total time: {end_time - start_time:.4f} seconds")
    logger.info(f"Finished at: {datetime.fromtimestamp(end_time).isoformat(timespec='milliseconds')}")
